apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.k8s.example.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
