output "talos_schematic_id" {
  description = "Talos Image Factory schematic ID."
  value       = talos_image_factory_schematic.this.id
}

output "talos_disk_image_url" {
  description = "Talos disk image URL generated by the Image Factory."
  value       = data.talos_image_factory_urls.this.urls.disk_image
}
