apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-test-data
  namespace: phase3-restore-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
