apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-wkr-03
auto: off
---
apiVersion: v1alpha1
kind: LinkConfig
name: ens18
up: true
addresses:
  - address: 192.0.2.23/24
routes:
  - gateway: 192.0.2.1
