defaultRules:
  create: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 120h

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: Europe/Berlin

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-csi
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  ingress:
    enabled: false

  initChownData:
    enabled: false

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

coreDns:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

prometheusOperator:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 14d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

prometheus-node-exporter:
  namespaceOverride: monitoring-node-exporter