apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami
  namespace: whoami
spec:
  secretName: whoami-tls
  dnsNames:
    - whoami.k8s.example.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
